proc="""<h2>Preprocessing</h2>
<p>In this tab, you can specify preprocessing steps that <em><strong>massoc </strong></em>should carry out before network inference. Some of these preprocessing steps can help you construct more informative networks. </p>
<h3>Prefix for saved files [-name]</h3>
<p>While the filenames generated by <em><strong>massoc </strong></em>already contain some information (e.g. taxonomic level or network tool), this prefix tells apart different <em><strong>massoc </strong></em>runs. </p>
<h3>Remove taxa with mean count below: [-min]</h3>
<p>Before a prevalence filter or rarefaction, you can remove taxa that have a count number below the supplied number. This can help remove singletons or low-abundance taxa. The removed counts are binned. </p>
<h3>Rarefy: [-rar]</h3>
<p>Rarefy to even depth or to a specific count number. If the supplied count number is higher than the sample count number, the sample is removed from the dataset. </p>
<p>For command line, specify <strong>-rar TRUE </strong>to rarefy to even depth or <strong>-rar </strong><strong>10000</strong> to rarefy to a specific count (10,000 in this case).</p>
<h3>Set prevalence filter in % [-prev]</h3>
<p>Filter taxa so only those remain that are present in the specified percentage of samples. The removed counts are binned. Prevalence filters can help remove spurious associations, and the default is therefore set to 20%.</p>
<h3>Split samples by metadata variable [-split]</h3>
<p>Select a metadata column to split the datasets by. For example, half of your datasets were taken from lakes, and the other half from rivers. If this is in the BIOM file, you can use it to split the BIOM file and run network inference on the samples separately (as well as on the original network). The resulting networks will have fewer spurious associations that are caused by the sampling strategy.</p>
<p>Note that the command line interface does not provide choices, so care should be taken to specify a correct metadata column. Moreover, this variable is also used to split datasets by cluster identity; in that case, the metadata selection is overriden and replaced by <strong>-split TRUE</strong>.</p>
<h3>Taxonomic levels to analyze [-levels]</h3>
<p>Select taxonomic levels to perform network inference on. The BIOM file is collapsed to different taxonomic levels, and the BIOM format <em>collapse </em>funtion is adapted to preserve the taxonomy up to the collapsed level. The identifiers of the collapsed taxa are also preserved in these BIOM files.</p>
<h3>Clustering algorithm [-cl]</h3>
<p>If there are no metadata available that explain microbiome structure, there may still be a structure present that could induce spurious associations (e.g. pH may explain microbiome clustering, but pH was not measured). In that case,&nbsp;<em><strong>massoc&nbsp;</strong></em>can run clustering algorithms: it first transforms the data using the centered log-ratio, and then ordinates them in PCA space. The PCA coordinates are used as input for the clustering algorithms. The cluster identities can either be added to the metadata, or used to split the BIOM file in multiple files.</p>
<p>In the command line interface, the algorithms are referred to as follows: K-means, DBSCAN, Gaussian, Spectral, Affinity. To split the datasets, <strong>-split </strong><strong>TRUE </strong>should be used. For characteristics of these algorithms, check out this <a href="http://scikit-learn.org/stable/auto_examples/cluster/plot_cluster_comparison.html">scikit-learn</a> example.</p>
<p>&nbsp;</p>
"""